[package]
name = "forte"
version = "1.0.0-alpha.2"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A low-overhead thread-pool with support for non-static async closures"
repository = "https://github.com/NthTensor/Forte"

[workspace]
resolver = "2"
members = ["ci"]
exclude = ["coz"]

[dependencies]
async-task = "4.7.1"
atomic-wait = "1.1.0"
tracing = { version = "0.1.41", features = ["release_max_level_off"] }
tracing-subscriber = "0.3.19"

[dev-dependencies]
# Required for comparison testing
divan = "0.1.17"
rayon = "1.10.0"
chili = "0.2"
# Used for A/B perf testing
criterion = { version = "0.5" }

[profile.release]
debug = true

[profile.bench]
debug = true

[lints.clippy]
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
undocumented_unsafe_blocks = "warn"
unwrap_or_default = "warn"

ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ref_as_ptr = "warn"

std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"

[lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "warn"
unused_qualifications = "warn"

unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }

# Add loom as a dependency for tests
[target.'cfg(loom)'.dependencies]
loom = { version = "0.7", features = [ "checkpoint" ] }

# Custom profile for Loom tests: enable release optimizations so that the loom
# tests are less slow, but don't disable debug assertions.
[profile.loom]
inherits = "test"
lto = true
opt-level = 3

[[test]]
name = "integration"
path = "tests/tests.rs"

[[bench]]
name = "fork_join"
harness = false
